
export enum TempMailErrorCodes {
    GENERIC_ERROR,
    INVALID_DOMAIN_NAME,
    BAD_JSON_POST_DATA,
    MISSING_DOMAIN_NAME,
    INVALID_METHOD,
    DOMAIN_TOO_LONG,
    NO_AUTH,
    RATE_LIMITED,
    INVALID_DOMAIN_PASSWORD,
    BAD_QUERY_STRING,
    
}
